#include "stdafx.h"
#include "BoardKey.h"

BoardKey::BoardKey()
{
	codeFromName["A"] = 0;			   ///< The A key
	codeFromName["B"] = 1;             ///< The B key
	codeFromName["C"] = 2;             ///< The C key
	codeFromName["D"] = 3;             ///< The D key
	codeFromName["E"] = 4;             ///< The E key
	codeFromName["F"] = 5;             ///< The F key
	codeFromName["G"] = 6;             ///< The G key
	codeFromName["H"] = 7;             ///< The H key
	codeFromName["I"] = 8;             ///< The I key
	codeFromName["J"] = 9;             ///< The J key
	codeFromName["K"] = 10;            ///< The K key
	codeFromName["L"] = 11;            ///< The L key
	codeFromName["M"] = 12;            ///< The M key
	codeFromName["N"] = 13;            ///< The N key
	codeFromName["O"] = 14;            ///< The O key
	codeFromName["P"] = 15;            ///< The P key
	codeFromName["Q"] = 16;            ///< The Q key
	codeFromName["R"] = 17;            ///< The R key
	codeFromName["S"] = 18;            ///< The S key
	codeFromName["T"] = 19;            ///< The T key
	codeFromName["U"] = 20;            ///< The U key
	codeFromName["V"] = 21;            ///< The V key
	codeFromName["W"] = 22;            ///< The W key
	codeFromName["X"] = 23;            ///< The X key
	codeFromName["Y"] = 24;            ///< The Y key
	codeFromName["Z"] = 25;            ///< The Z key
	codeFromName["0"] = 26;            ///< The 0 key
	codeFromName["1"] = 27;            ///< The 1 key
	codeFromName["2"] = 28;            ///< The 2 key
	codeFromName["3"] = 29;            ///< The 3 key
	codeFromName["4"] = 30;            ///< The 4 key
	codeFromName["5"] = 31;            ///< The 5 key
	codeFromName["6"] = 32;            ///< The 6 key
	codeFromName["7"] = 33;            ///< The 7 key
	codeFromName["8"] = 34;            ///< The 8 key
	codeFromName["9"] = 35;            ///< The 9 key
	codeFromName["Escape"] = 36;       ///< The Escape key
	codeFromName["LControl"] = 37;     ///< The left Control key
	codeFromName["LShift"] = 38;       ///< The left Shift key
	codeFromName["LAlt"] = 39;         ///< The left Alt key
	codeFromName["LSystem"] = 40;      ///< The left OS specific key: window (Windows and Linux), apple (MacOS X), ...
	codeFromName["RControl"] = 41;     ///< The right Control key
	codeFromName["RShift"] = 42;       ///< The right Shift key
	codeFromName["RAlt"] = 43;         ///< The right Alt key
	codeFromName["RSystem"] = 44;      ///< The right OS specific key: window (Windows and Linux), apple (MacOS X), ...
	codeFromName["Menu"] = 45;         ///< The Menu key
	codeFromName["LBracket"] = 46;     ///< The [ key
	codeFromName["RBracket"] = 47;     ///< The ] key
	codeFromName["Semicolon"] = 48;    ///< The ; key
	codeFromName["Comma"] = 49;        ///< The , key
	codeFromName["Period"] = 50;       ///< The . key
	codeFromName["Quote"] = 51;        ///< The ' key
	codeFromName["Slash"] = 52;        ///< The / key
	codeFromName["Backslash"] = 53;    ///< The \ key
	codeFromName["Tilde"] = 54;        ///< The ~ key
	codeFromName["Equal"] = 55;        ///< The = key
	codeFromName["Hyphen"] = 56;       ///< The - key (hyphen)
	codeFromName["Space"] = 57;        ///< The Space key
	codeFromName["Enter"] = 58;        ///< The Enter/Return keys
	codeFromName["Backspace"] = 59;    ///< The Backspace key
	codeFromName["Tab"] = 60;          ///< The Tabulation key
	codeFromName["PageUp"] = 61;       ///< The Page up key
	codeFromName["PageDown"] = 62;     ///< The Page down key
	codeFromName["End"] = 63;          ///< The End key
	codeFromName["Home"] = 64;         ///< The Home key
	codeFromName["Insert"] = 65;       ///< The Insert key
	codeFromName["Delete"] = 66;       ///< The Delete key
	codeFromName["Add"] = 67;          ///< The + key
	codeFromName["Subtract"] = 68;     ///< The - key (minus, usually from numpad)
	codeFromName["Multiply"] = 69;     ///< The * key
	codeFromName["Divide"] = 70;       ///< The / key
	codeFromName["Left"] = 71;         ///< Left arrow
	codeFromName["Right"] = 72;        ///< Right arrow
	codeFromName["Up"] = 73;           ///< Up arrow
	codeFromName["Down"] = 74;         ///< Down arrow
	codeFromName["Numpad0"] = 75;      ///< The numpad 0 key
	codeFromName["Numpad1"] = 76;      ///< The numpad 1 key
	codeFromName["Numpad2"] = 77;      ///< The numpad 2 key
	codeFromName["Numpad3"] = 78;      ///< The numpad 3 key
	codeFromName["Numpad4"] = 79;      ///< The numpad 4 key
	codeFromName["Numpad5"] = 80;      ///< The numpad 5 key
	codeFromName["Numpad6"] = 81;      ///< The numpad 6 key
	codeFromName["Numpad7"] = 82;      ///< The numpad 7 key
	codeFromName["Numpad8"] = 83;      ///< The numpad 8 key
	codeFromName["Numpad9"] = 84;      ///< The numpad 9 key
	codeFromName["F1"] = 85;           ///< The F1 key
	codeFromName["F2"] = 86;           ///< The F2 key
	codeFromName["F3"] = 87;           ///< The F3 key
	codeFromName["F4"] = 88;           ///< The F4 key
	codeFromName["F5"] = 89;           ///< The F5 key
	codeFromName["F6"] = 90;           ///< The F6 key
	codeFromName["F7"] = 91;           ///< The F7 key
	codeFromName["F8"] = 92;           ///< The F8 key
	codeFromName["F9"] = 93;           ///< The F9 key
	codeFromName["F10"] = 94;          ///< The F10 key
	codeFromName["F11"] = 95;          ///< The F11 key
	codeFromName["F12"] = 96;          ///< The F12 key
	codeFromName["F13"] = 97;          ///< The F13 key
	codeFromName["F14"] = 98;          ///< The F14 key
	codeFromName["F15"] = 99;          ///< The F15 key
	codeFromName["Pause"] = 100;       ///< The Pause key

	////////////////////////////////////////////////////////

	nameFromCode[0] = "A";			   ///< The A key
	nameFromCode[1] = "B";             ///< The B key
	nameFromCode[2] = "C";             ///< The C key
	nameFromCode[3] = "D";             ///< The D key
	nameFromCode[4] = "E";             ///< The E key
	nameFromCode[5] = "F";             ///< The F key
	nameFromCode[6] = "G";             ///< The G key
	nameFromCode[7] = "H";             ///< The H key
	nameFromCode[8] = "I";             ///< The I key
	nameFromCode[9] = "J";             ///< The J key
	nameFromCode[10] = "K";            ///< The K key
	nameFromCode[11] = "L";            ///< The L key
	nameFromCode[12] = "M";            ///< The M key
	nameFromCode[13] = "N";            ///< The N key
	nameFromCode[14] = "O";            ///< The O key
	nameFromCode[15] = "P";            ///< The P key
	nameFromCode[16] = "Q";            ///< The Q key
	nameFromCode[17] = "R";            ///< The R key
	nameFromCode[18] = "S";            ///< The S key
	nameFromCode[19] = "T";            ///< The T key
	nameFromCode[20] = "U";            ///< The U key
	nameFromCode[21] = "V";            ///< The V key
	nameFromCode[22] = "W";            ///< The W key
	nameFromCode[23] = "X";            ///< The X key
	nameFromCode[24] = "Y";            ///< The Y key
	nameFromCode[25] = "Z";            ///< The Z key
	nameFromCode[26] = "0";            ///< The 0 key
	nameFromCode[27] = "1";            ///< The 1 key
	nameFromCode[28] = "2";            ///< The 2 key
	nameFromCode[29] = "3";            ///< The 3 key
	nameFromCode[30] = "4";            ///< The 4 key
	nameFromCode[31] = "5";            ///< The 5 key
	nameFromCode[32] = "6";            ///< The 6 key
	nameFromCode[33] = "7";            ///< The 7 key
	nameFromCode[34] = "8";            ///< The 8 key
	nameFromCode[35] = "9";            ///< The 9 key
	nameFromCode[36] = "Escape";       ///< The Escape key
	nameFromCode[37] = "LControl";     ///< The left Control key
	nameFromCode[38] = "LShift";       ///< The left Shift key
	nameFromCode[39] = "LAlt";         ///< The left Alt key
	nameFromCode[40] = "LSystem";      ///< The left OS specific key: window (Windows and Linux), apple (MacOS X), ...
	nameFromCode[41] = "RControl";     ///< The right Control key
	nameFromCode[42] = "RShift";       ///< The right Shift key
	nameFromCode[43] = "RAlt";         ///< The right Alt key
	nameFromCode[44] = "RSystem";      ///< The right OS specific key: window (Windows and Linux), apple (MacOS X), ...
	nameFromCode[45] = "Menu";         ///< The Menu key
	nameFromCode[46] = "LBracket";     ///< The [ key
	nameFromCode[47] = "RBracket";     ///< The ] key
	nameFromCode[48] = "Semicolon";    ///< The ; key
	nameFromCode[49] = "Comma";        ///< The , key
	nameFromCode[50] = "Period";       ///< The . key
	nameFromCode[51] = "Quote";        ///< The ' key
	nameFromCode[52] = "Slash";        ///< The / key
	nameFromCode[53] = "Backslash";    ///< The \ key
	nameFromCode[54] = "Tilde";        ///< The ~ key
	nameFromCode[55] = "Equal";        ///< The = key
	nameFromCode[56] = "Hyphen";       ///< The - key (hyphen)
	nameFromCode[57] = "Space";        ///< The Space key
	nameFromCode[58] = "Enter";        ///< The Enter/Return keys
	nameFromCode[59] = "Backspace";    ///< The Backspace key
	nameFromCode[60] = "Tab";          ///< The Tabulation key
	nameFromCode[61] = "PageUp";       ///< The Page up key
	nameFromCode[62] = "PageDown";     ///< The Page down key
	nameFromCode[63] = "End";          ///< The End key
	nameFromCode[64] = "Home";         ///< The Home key
	nameFromCode[65] = "Insert";       ///< The Insert key
	nameFromCode[66] = "Delete";       ///< The Delete key
	nameFromCode[67] = "Add";          ///< The + key
	nameFromCode[68] = "Subtract";     ///< The - key (minus, usually from numpad)
	nameFromCode[69] = "Multiply";     ///< The * key
	nameFromCode[70] = "Divide";       ///< The / key
	nameFromCode[71] = "Left";         ///< Left arrow
	nameFromCode[72] = "Right";        ///< Right arrow
	nameFromCode[73] = "Up";           ///< Up arrow
	nameFromCode[74] = "Down";         ///< Down arrow
	nameFromCode[75] = "Numpad0";      ///< The numpad 0 key
	nameFromCode[76] = "Numpad1";      ///< The numpad 1 key
	nameFromCode[77] = "Numpad2";      ///< The numpad 2 key
	nameFromCode[78] = "Numpad3";      ///< The numpad 3 key
	nameFromCode[79] = "Numpad4";      ///< The numpad 4 key
	nameFromCode[80] = "Numpad5";      ///< The numpad 5 key
	nameFromCode[81] = "Numpad6";      ///< The numpad 6 key
	nameFromCode[82] = "Numpad7";      ///< The numpad 7 key
	nameFromCode[83] = "Numpad8";      ///< The numpad 8 key
	nameFromCode[84] = "Numpad9";      ///< The numpad 9 key
	nameFromCode[85] = "F1";           ///< The F1 key
	nameFromCode[86] = "F2";           ///< The F2 key
	nameFromCode[87] = "F3";           ///< The F3 key
	nameFromCode[88] = "F4";           ///< The F4 key
	nameFromCode[89] = "F5";           ///< The F5 key
	nameFromCode[90] = "F6";           ///< The F6 key
	nameFromCode[91] = "F7";           ///< The F7 key
	nameFromCode[92] = "F8";           ///< The F8 key
	nameFromCode[93] = "F9";           ///< The F9 key
	nameFromCode[94] = "F10";          ///< The F10 key
	nameFromCode[95] = "F11";          ///< The F11 key
	nameFromCode[96] = "F12";          ///< The F12 key
	nameFromCode[97] = "F13";          ///< The F13 key
	nameFromCode[98] = "F14";          ///< The F14 key
	nameFromCode[99] = "F15";          ///< The F15 key
	nameFromCode[100] = "Pause";       ///< The Pause key
}